# Generated by Django 2.2 on 2020-03-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('totalprice', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sub', models.CharField(max_length=100)),
                ('house_area', models.FloatField()),
                ('house_type', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=20)),
                ('dircetion', models.CharField(max_length=20)),
                ('renovation', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
