# Generated by Django 2.2 on 2020-03-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_view', '0003_auto_20200323_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house_base',
            options={'ordering': ['-id']},
        ),
    ]
