# Generated by Django 2.2 on 2020-04-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_view', '0004_auto_20200329_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_base',
            name='house_area',
            field=models.FloatField(),
        ),
    ]
